[package]
name = "anydo"
version = "0.1.0"
authors = ["Riku Inoue <riku.inoue@shiroyagi.co.jp>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.11"
chrono = { version = "0.4", features = ["serde"]}
rand = "0.5.0-pre.1"